name: Build and Release windows only
on: [workflow_dispatch]
jobs:
  build:
    name: Build Apps
    runs-on: windows-latest
    steps:
      - name: Export Release Timestamp
        run: echo "APP_VERSION=v$(date +'%Y.%m.%d.%H.%M.%S')" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.0'
          channel: 'stable'
      - name: Install pub Dependencies
        run: flutter pub get
      - name: Build Android App
        run: flutter build windows --release
      - name: Build Android App
        run: flutter pub run msix:create
      - name: Upload WSA
        uses: actions/upload-artifact@v2
        with:
          name: App
          path: "build/windows/runner/Release/*.msix"
